version: '3'

services:
  flask-app:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask_app        # Denna e viktig
    environment:
      DB_HOST: postgresql_db         # Sätter vår DB_HOST env till att peka till postgresql_db
    ports:
      - "5000:5000"
    depends_on:
      - postgresql

  postgresql:
    image: postgres:latest
    container_name: postgresql_db    # Denna med
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"

  flask-ui:
    build:
      context: ./app/ui
      dockerfile: Dockerfile
    container_name: flask_ui
    environment:
      API_HOST: flask_app
    ports:
      - "80:80"
    depends_on:
      - flask-app
    extra_hosts:
      - "host.docker.internal:host-gateway"