version: '3'

services:
  flask-app:
    build: ./app
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - DATABASE_URI=sqlite:///app.db

  db:
    image: "postgres:latest"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=database
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
