version: '3'

services:
  falsk-api:
    build:
      context: ./app
      dockerfile: ./src/api/Dockerfile
    container_name: falsk_api
    environment:
      DB_HOST: postgresql_db
    ports:
      - "5000:5000"
    depends_on:
      - postgresql
    
  flask-user-management:
    build:
      context: ./app
      dockerfile: ./src/user_management/Dockerfile
    container_name: user_management
    environment:
      DB_HOST: postgresql_db
    ports:
      - "5001:5001"
    depends_on:
      - postgresql

  flask-ui:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: flask_ui
    environment:
      API_HOST: falsk_api
    ports:
      - "8080:80"
    depends_on:
      - falsk-api
      - flask-user-management
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgresql:
    image: postgres:latest
    container_name: postgresql_db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: database
    ports:
      - "5432:5432"